import { Public_Sans } from "next/font/google";
import "./globals.css";
import MainNavigation from "@/components/layout/main-navigation";
import Footer from "@/components/layout/footer";

const inter = Public_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "錫儀企業有限公司",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh_Hant">
      <body className={inter.className}>
        <MainNavigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
